kind: Service
apiVersion: v1
metadata:
  name: customer-service
spec:
  type: ClusterIP
  selector:
    app: spring-cloud-customer-service
  ports:
  - protocol: TCP
    port: 8092
    targetPort: 8092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-customer-service
  labels:
    app: spring-cloud-customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-customer-service
  template:
    metadata:
      labels:
        app: spring-cloud-customer-service
        version: latest
    spec:
      containers:
      - name: spring-cloud-customer-service
        image: 192.168.0.8:5000/customer-service:latest
        ports:
        - name: http
          containerPort: 8092